// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Storage.Data;

#nullable disable

namespace Server.Storage.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20260624191014_Auto_20260624_221000")]
    partial class Auto_20260624_221000
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Storage.Models.FileMetadataEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_file_metadata_entries");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_metadata_entries_file_id");

                    b.ToTable("file_metadata_entries", (string)null);
                });

            modelBuilder.Entity("Server.Storage.Models.StorageDirectory", b =>
                {
                    b.Property<Guid>("DirectoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("directory_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("directory_name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("normalized_path");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentDirectoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_directory_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DirectoryId")
                        .HasName("pk_storage_directories");

                    b.HasIndex("DirectoryId")
                        .HasDatabaseName("ix_storage_directories_directory_id");

                    b.HasIndex("OwnerId", "NormalizedPath")
                        .HasDatabaseName("ix_storage_directories_owner_id_normalized_path");

                    b.HasIndex("OwnerId", "ParentDirectoryId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_directories_owner_id_parent_directory_id_normalized");

                    b.ToTable("storage_directories", (string)null);
                });

            modelBuilder.Entity("Server.Storage.Models.StorageFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("bucket_name");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_name");

                    b.Property<string>("NormalizedPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("normalized_path");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentDirectoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_directory_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("FileId")
                        .HasName("pk_storage_files");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_storage_files_file_id");

                    b.HasIndex("OwnerId", "NormalizedPath")
                        .HasDatabaseName("ix_storage_files_owner_id_normalized_path");

                    b.ToTable("storage_files", (string)null);
                });

            modelBuilder.Entity("Server.Storage.Models.StorageFileAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("GroupId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_storage_file_access");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_storage_file_access_file_id");

                    b.ToTable("storage_file_access", (string)null);
                });

            modelBuilder.Entity("Server.Storage.Models.StorageNonce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean")
                        .HasColumnName("consumed");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operation_name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_storage_nonces");

                    b.HasIndex("OwnerId", "OperationName", "Token")
                        .HasDatabaseName("ix_storage_nonces_owner_id_operation_name_token");

                    b.ToTable("storage_nonces", (string)null);
                });

            modelBuilder.Entity("Server.Storage.Models.StorageSharedLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("AllowedGroups")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_groups");

                    b.PrimitiveCollection<string>("AllowedUsers")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_users");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_storage_shared_links");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_storage_shared_links_file_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_shared_links_token");

                    b.ToTable("storage_shared_links", (string)null);
                });

            modelBuilder.Entity("Server.Storage.Models.FileMetadataEntry", b =>
                {
                    b.HasOne("Server.Storage.Models.StorageFile", "File")
                        .WithMany("Metadata")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_metadata_entries_storage_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Server.Storage.Models.StorageFileAccess", b =>
                {
                    b.HasOne("Server.Storage.Models.StorageFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_file_access_storage_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Server.Storage.Models.StorageSharedLink", b =>
                {
                    b.HasOne("Server.Storage.Models.StorageFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_shared_links_storage_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Server.Storage.Models.StorageFile", b =>
                {
                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
